# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0002_auto_20170904_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
