# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0003_auto_20170904_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortened_slug',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
